export const BUY_GARDEN_SALAD = "BUY_GARDEN_SALAD";
export const BUY_CEASARS_SALAD = "BUY_CEASARS_SALAD";
export const RETURN_GARDEN_SALAD = "RETURN_GARDEN_SALAD";
export const RETURN_CEASARS_SALAD = "RETURN_CEASARS_SALAD";
