export const BUY_LASAGNA = "BUY_LASAGNA";
export const BUY_PANZEROTTI = "BUY_PANZEROTTI";
export const BUY_BEEFONARA = "BUY_BEEFONARA";

export const RETURN_LASAGNA = "RETURN_LASAGNA";
export const RETURN_PANZEROTTI = "RETURN_PANZEROTTI";
export const RETURN_BEEFONARA = "RETURN_BEEFONARA";
